const Symbols=[{"Symbol":"AAPL",
                 "Company":"Apple"},
                { "Symbol":"F",
                 "Company":"Ford"},
                 {  "Symbol":"ACB",
                 "Company":"Aurora Cannabis"},         
                 {  "Symbol":"T",
                 "Company":"AT&T"} ,
                 {"Symbol":"AMZN",
                 "Company":"Amazon"},
                 {"Symbol":"AMD",
                 "Company":"AMD"},
                 {"Symbol":"VZ",
                 "Company":"Verizon"},
                 {"Symbol":"NVDA",
                 "Company":"NVIDIA"},
                 {"Symbol":"NTDOY",
                 "Company":"Nintendo"},
                 {"Symbol":"TCEHY",
                 "Company":"Tencent"},
                 {"Symbol":"BP",
                 "Company":"British Petroleu" },
                 {"Symbol":"WMT",
                 "Company":"Walmart" },
                 {"Symbol":"ROKU",
                 "Company":"Roku" },
                 {"Symbol":"SAVE",
                 "Company":"Spirit Airline" },
                 {"Symbol":"V",
                 "Company":"Visa" }
                                  

                 ]
export default Symbols